### ISSUE TITLE
lab-00: wrong hard-coded PREFIX

### ISSUE THREAD

**Issue by BenoitDherin** [jarokaz/mlops-labs#52]
In the [verify-infra.ipynb](https://github.com/jarokaz/mlops-labs/blob/master/labs/lab-00-environment-setup/verify-infra.ipynb) notebook: 

The command

``` bash
!gcloud container clusters get-credentials ksalama-mlops-dev-cluster --region=europe-west1-b
```

should be replace by 

``` bash
PREFIX=<YOUR-OWN-PREFIX>
!gcloud container clusters get-credentials PREFIX-dev-cluster --region=europe-west1-b
```

**Comment by BenoitDherin** [comment]
Actually, the ZONE and the cluster NAMESPACE are also hardcoded to different values than the defaults. The following command worked:

```bash
%%bash

PREFIX=<YOUR-PREFIX>
ZONE=<YOUR-ZONE>
NAMESPACE=<YOUR-NAMESPACE>

gcloud container clusters get-credentials $PREFIX-cluster --zone $ZONE

echo "https://"$(kubectl describe configmap inverse-proxy-config -n $NAMESPACE | \
grep "googleusercontent.com")
```

**Comment by BenoitDherin** [comment]
Similar issue in the following cell (where the NAMESPACE should be either the default one "kubeflow" or left to be updated by the user):

```
import kfp
 
HOST_URL = ''
NAMESPACE = 'kfp'
  
client = kfp.Client(host=HOST_URL, namespace=NAMESPACE)
[pipeline.name for pipeline in client.list_pipelines().pipelines]
```

**Comment by ksalama** [comment]
Thanks @BenoitDherin for this. I have updated the notebooks with your suggestions. We can also go ahead an submit PRs
