### ISSUE TITLE
lab01-granting rote to cloudbuild

### ISSUE THREAD

**Issue by BenoitDherin** [jarokaz/mlops-labs#55]
From the [README.md](https://github.com/jarokaz/mlops-labs/blob/master/labs/lab-01-environment-notebook/README.md) link:

![image](https://user-images.githubusercontent.com/5290305/74161100-55c22600-4c16-11ea-9b76-b817ded19bd3.png)

it not clear how to grant the Cloud Build service account the Project Editor role.

Is this the right documentation?

**Comment by jarokaz** [comment]
Yes. This may be confusing. I am going to replace with a gcloud command.

**Comment by jarokaz** [comment]
Done. Updated README.md with the gcloud command
