### ISSUE TITLE
lab-11: Image name mismatch between labs

### ISSUE THREAD

**Issue by BenoitDherin** [jarokaz/mlops-labs#59]
In the notebook [covertype_experimentation.ipynb](https://github.com/jarokaz/mlops-labs/blob/master/labs/lab-11-caip-containers/covertype_experimentation.ipynb), the image name is "trainer_image" while the image uploaded to the project registry in lab-00 and lab-01 is "mlops-dev" in the instruction [README](https://github.com/jarokaz/mlops-labs/tree/master/labs/lab-01-environment-notebook).

In [covertype_experimentation.ipynb](https://github.com/jarokaz/mlops-labs/blob/master/labs/lab-11-caip-containers/covertype_experimentation.ipynb):

```
IMAGE_NAME='trainer_image'
IMAGE_TAG='latest'
IMAGE_URI='gcr.io/{}/{}:{}'.format(PROJECT_ID, IMAGE_NAME, IMAGE_TAG)
IMAGE_URI
```

In [lab 01-README](https://github.com/jarokaz/mlops-labs/tree/master/labs/lab-01-environment-notebook):

```
IMAGE_NAME=mlops-dev
TAG=latest
IMAGE_URI="gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${TAG}"
```

In [Lab-00](https://github.com/jarokaz/mlops-labs/blob/master/labs/lab-00-environment-setup/install.sh#L43): It's also "mlops-dev" but with a different tag

```
IMAGE_NAME=mlops-dev
TAG=TF115-TFX015-KFP136
IMAGE_URI="gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${TAG}"
```

In [Lab-00-simplified](https://github.com/jarokaz/mlops-labs/blob/master/labs/lab-00-environment-setup-simplified/install.sh#L41-L42), it's "mlops-labs-image":

```
IMAGE_NAME=mlops-labs-image
TAG=latest
```

What about having everywhere (I think it's more informative that "mlops-dev or "trainer-image"?:

```
IMAGE_NAME=TF115-TFX015-KFP136
TAG=latest
```

**Comment by jarokaz** [comment]
Modified  a name of a custom container image used as an AI Platform Notebook base image to be mlops-dev:latest.
